version: '2'
services:
  bttv:
    build: .
    restart: unless-stopped
    container_name: telegram-bttv
    command: node emotes_bttv.js
    environment:
      BOT_TOKEN: ${TELEGRAM_TOKEN_BTTV}
  ffz:
    build: .
    restart: unless-stopped
    container_name: telegram-ffz
    command: node emotes_ffz.js
    environment:
      BOT_TOKEN: ${TELEGRAM_TOKEN_FFZ}
